services:
  scrapper:
    build: .
    command: ["node", "src/push.js"]
    environment:
      PUSH_URL: "https://ip-tv.hatip.dev/scrapper/api/streams"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1536M
