apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ip-tv-addon

resources:
  - namespace.yaml
  - deployment.yaml

images:
  - name: ghcr.io/hatip5656/ip-tv-scrapper
    newTag: latest
